name = "Squeegee"
uuid = "bf09cb93-fefd-43ac-9a56-6511d16be4da"
authors = ["Kai Aragaki"]
version = "1.0.0-DEV"

[compat]
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
